// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCabUfy0a6lpw-KhbMWQwMbQvkmkYh8kdA',
    appId: '1:543414932327:web:a3dadb358232598d04d5c2',
    messagingSenderId: '543414932327',
    projectId: 'ka-jobs',
    authDomain: 'ka-jobs.firebaseapp.com',
    storageBucket: 'ka-jobs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdoiRWWm2FGChCFF8lhSCI3I6jbGKg3HM',
    appId: '1:543414932327:android:c11a30132981b02d04d5c2',
    messagingSenderId: '543414932327',
    projectId: 'ka-jobs',
    storageBucket: 'ka-jobs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFVpB2IP3VxM_7z2OYZ3m9Q1WG65Xwuug',
    appId: '1:543414932327:ios:01f022ef073b1f4204d5c2',
    messagingSenderId: '543414932327',
    projectId: 'ka-jobs',
    storageBucket: 'ka-jobs.firebasestorage.app',
    iosBundleId: 'com.example.kamaliniApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFVpB2IP3VxM_7z2OYZ3m9Q1WG65Xwuug',
    appId: '1:543414932327:ios:01f022ef073b1f4204d5c2',
    messagingSenderId: '543414932327',
    projectId: 'ka-jobs',
    storageBucket: 'ka-jobs.firebasestorage.app',
    iosBundleId: 'com.example.kamaliniApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCabUfy0a6lpw-KhbMWQwMbQvkmkYh8kdA',
    appId: '1:543414932327:web:b2ab7d0248e560b104d5c2',
    messagingSenderId: '543414932327',
    projectId: 'ka-jobs',
    authDomain: 'ka-jobs.firebaseapp.com',
    storageBucket: 'ka-jobs.firebasestorage.app',
  );

}